language: python
python:
  - "2.7"
#  - "3.2"
#  - "3.4"
  - "3.5"
#  - "nightly"
# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
  - "sudo apt-get update"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - sudo apt-get install python-qt4
  - pip install pep8
  - "ln -s /usr/lib/python2.7/dist-packages/PyQt4/ $VIRTUAL_ENV/lib/python2.7/site-packages/"
  - "ln -s /usr/lib/python2.7/dist-packages/sip.so $VIRTUAL_ENV/lib/python2.7/site-packages/"
  - pip install pylint
  - sudo apt-get -y install python3-pyqt5
script:
 - python pylint-recursive.py
 - nosetests
notifications:
  irc: false
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fdaa9e93e1a5b657bed
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
