language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
# command to install dependencies
before_install:
  - "sudo apt-get update"
install:
  - "sudo apt-get install python-pyqt5 python4-pyqt5"
script: 
  nosetests
notifications:
  irc: false
  email: false
