language: python
python:
  - "2.7"
#  - "3.2"
#  - "3.4"
#  - "3.5"
#  - "nightly"
# command to install dependencies
before_install:
  - "sudo apt-get update"
install:
  - "sudo apt-get install python-qt4"
  - "pip install pep8"
  - "ln -s /usr/lib/python2.7/dist-packages/PyQt4/ $VIRTUAL_ENV/lib/python2.7/site-packages/"
  - "ln -s /usr/lib/python2.7/dist-packages/sip.so $VIRTUAL_ENV/lib/python2.7/site-packages/"
  - "sudo start xvfb"
script: 
  nosetests
notifications:
  irc: false
  email: false
